"""Deploy the read-only Orrery demo to a HuggingFace Docker Space.

Uploads the working tree (filtered) to the Space repo with huggingface_hub. The
large demo seed lives in a separate private Dataset repository and the Docker
build downloads the immutable revision recorded in demo.lock.json.

Three commits per deploy:
  1. the filtered repo tree (Dockerfile, backend, frontend, deploy/)
  2. deploy/hf-space/README_SPACE.md → README.md  (Space card + frontmatter)
  3. the root .dockerignore → .dockerignore

Prerequisites:
  - demo.lock.json has been generated by publish_seed_snapshot.py
  - a HuggingFace token with Space write access (env HF_TOKEN)
  - the Space has a read-only HF_SEED_TOKEN secret for the private Dataset

Usage:
    uv run python deploy/hf-space/deploy.py --repo-id <user>/orrery-demo [--create]

After the first deploy, set the Space secret GEMINI_API_KEY (Settings →
Variables and secrets) to enable semantic search on the Gemini collections.
"""

import argparse
import re
import sys
from pathlib import Path

from huggingface_hub import HfApi

REPO_ROOT = Path(__file__).resolve().parents[2]
DEPLOY_DIR = REPO_ROOT / "deploy" / "hf-space"
# Everything the Dockerfile does not need stays out of the Space repo. The
# live data stores are the critical ones (main.duckdb is ~23 GB on disk).
# NOTE: fnmatch patterns match the FULL relative path — "benchmarks/*" does
# not cover "interpretability_backend/benchmarks/*", and ".env" does not
# cover nested ".env" files; both need explicit entries.
IGNORE_PATTERNS = [
    ".git/*",
    ".git*",
    ".venv/*",
    ".claude/*",
    ".codex/*",
    "**/__pycache__/*",
    "**/*.pyc",
    ".pytest_cache/*",
    ".ruff_cache/*",
    ".DS_Store",
    "**/.DS_Store",
    # secrets — root AND nested (e.g. embedding_visualization/.env.local)
    ".env",
    ".env.*",
    "**/.env",
    "**/.env.*",
    # not needed to build the image
    "docs/*",
    "documentation/*",
    "gallery/*",
    "benchmarks/*",
    "references/*",
    "neuronpedia/*",
    "node_modules/*",
    "Papers/*",
    # experiments + local data (includes copyrighted corpora, e.g. Lacan TSVs
    # under interpretability_experiments/ — must never reach the public repo)
    "interpretability_backend/interpretability_experiments/*",
    "interpretability_backend/test/*",
    "interpretability_backend/benchmarks/*",
    # frontend build artifacts / deps (rebuilt in the image)
    "embedding_visualization/node_modules/*",
    "embedding_visualization/.next/*",
    "embedding_visualization/out/*",
    "embedding_visualization/coverage/*",
    "embedding_visualization/Users/*",
    "**/tsconfig.tsbuildinfo",
    "**/target/*",
    # backend live stores + local-only data (the demo seed is downloaded from
    # its locked private Dataset revision during the Docker build)
    "interpretability_backend/resources/main.duckdb",
    "interpretability_backend/resources/main.duckdb.*",
    "interpretability_backend/resources/vector_db/*",
    "interpretability_backend/resources/seed/*",
    "interpretability_backend/resources/seed_demo/*",
    "interpretability_backend/resources/uploads/*",
    "interpretability_backend/resources/job_state.json",
    "interpretability_backend/resources/sae_labels/*",
    "interpretability_backend/resources/sae_vectors/*",
    "interpretability_backend/resources/refusal_direction/*",
    "interpretability_backend/resources/experiments/*",
    "interpretability_backend/resources/extracted_activations/*",
    "interpretability_backend/resources/probing_results/*",
    "interpretability_backend/resources/psycolinguistics/*",
    "interpretability_backend/resources/acl_anthology/*",
    "interpretability_backend/resources/datasets/*",
]


def space_direct_url(repo_id: str) -> str:
    """The *.hf.space host — HF's stable embedding surface for the Space."""
    subdomain = re.sub(r"[^a-z0-9-]", "-", repo_id.lower())
    return f"https://{subdomain}.hf.space"


def render_space_readme(repo_id: str) -> bytes:
    """README_SPACE.md with its URL placeholders resolved for this Space.

    The repo id lives only in CI variables (HF_SPACE_REPO_ID), so the README
    keeps {{SPACE_URL}} / {{SPACE_DIRECT_URL}} placeholders and the deploy
    resolves them — that is what makes the "What to try" preset links work.
    """
    text = (DEPLOY_DIR / "README_SPACE.md").read_text(encoding="utf-8")
    text = text.replace("{{SPACE_URL}}", f"https://huggingface.co/spaces/{repo_id}")
    text = text.replace("{{SPACE_DIRECT_URL}}", space_direct_url(repo_id))
    return text.encode("utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--repo-id", required=True, help="Space repo, e.g. <user>/orrery-demo")
    parser.add_argument("--create", action="store_true", help="create the Space if it is missing")
    parser.add_argument("--private", action="store_true", help="create the Space as private")
    args = parser.parse_args()

    lock_path = (
        REPO_ROOT
        / "interpretability_backend"
        / "config"
        / "seed_snapshots"
        / "demo.lock.json"
    )
    if not lock_path.exists():
        print(
            f"ERROR: immutable demo seed lock not found at {lock_path}.\n"
            "Build and publish demo.json first — see documentation/HF_SPACE_DEMO.md.",
            file=sys.stderr,
        )
        return 1

    api = HfApi()

    if args.create:
        api.create_repo(
            repo_id=args.repo_id,
            repo_type="space",
            space_sdk="docker",
            private=args.private,
            exist_ok=True,
        )
        print(f"[deploy] space ensured: {args.repo_id}")

    print(f"[deploy] uploading filtered tree from {REPO_ROOT} (large files go via LFS)…")
    api.upload_folder(
        folder_path=str(REPO_ROOT),
        repo_id=args.repo_id,
        repo_type="space",
        ignore_patterns=IGNORE_PATTERNS,
        delete_patterns=["interpretability_backend/resources/seed_demo/**"],
        commit_message="Deploy Orrery demo",
    )

    print("[deploy] uploading Space README (frontmatter) and .dockerignore…")
    api.upload_file(
        path_or_fileobj=render_space_readme(args.repo_id),
        path_in_repo="README.md",
        repo_id=args.repo_id,
        repo_type="space",
        commit_message="Space README",
    )
    api.upload_file(
        path_or_fileobj=str(REPO_ROOT / ".dockerignore"),
        path_in_repo=".dockerignore",
        repo_id=args.repo_id,
        repo_type="space",
        commit_message="Space .dockerignore",
    )

    space_url = f"https://huggingface.co/spaces/{args.repo_id}"
    print(
        f"\nDeployed. Watch the build at {space_url}\n"
        "Reminder: set the Space secret GEMINI_API_KEY to enable semantic "
        "search on the EMNLP + xkcd collections."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
