"""Deploy the read-only Orrery demo to a HuggingFace Docker Space.

Uploads the working tree (filtered) to the Space repo with huggingface_hub. The
large demo seed lives in a separate private Dataset repository and the Docker
build downloads the immutable revision recorded in demo.lock.json.

One settings write plus three commits per deploy:
  0. the Space Variable NEXT_PUBLIC_SITE_URL (the *.hf.space origin the
     frontend bakes into its social-preview metadata; HF passes Variables to
     the Docker build as build-args)
  1. deploy/hf-space/README_SPACE.md → README.md  (Space card + frontmatter)
  2. the filtered repo tree (Dockerfile, backend, frontend, deploy/)
  3. the root .dockerignore → .dockerignore

Prerequisites:
  - demo.lock.json has been generated by publish_seed_snapshot.py
  - a HuggingFace token with Space write access (env HF_TOKEN)
  - the Space has a read-only HF_SEED_TOKEN secret for the private Dataset

Usage:
    uv run python deploy/hf-space/deploy.py --repo-id <user>/orrery-demo [--create]

After the first deploy, set the Space secret GEMINI_API_KEY (Settings →
Variables and secrets) to enable semantic search on the Gemini collections.
"""

import argparse
import re
import sys
from pathlib import Path

from huggingface_hub import HfApi
from huggingface_hub.errors import HfHubHTTPError

REPO_ROOT = Path(__file__).resolve().parents[2]
DEPLOY_DIR = REPO_ROOT / "deploy" / "hf-space"
# The social-preview image, relative to the repo root. It is the Next.js
# file-convention Open Graph image (served by the app at /opengraph-image.jpg)
# AND the Space card thumbnail: the README frontmatter points at this file in
# the Space repo (Hub-served, so the card works even while the Space sleeps).
SOCIAL_PREVIEW_PATH = "embedding_visualization/app/opengraph-image.jpg"
# Space Variable carrying the public origin; the root Dockerfile declares a
# matching ARG so the frontend build can set Next's metadataBase from it.
SITE_URL_VARIABLE = "NEXT_PUBLIC_SITE_URL"
# Everything the Dockerfile does not need stays out of the Space repo. The
# live data stores are the critical ones (main.duckdb is ~23 GB on disk).
# NOTE: fnmatch patterns match the FULL relative path — "benchmarks/*" does
# not cover "interpretability_backend/benchmarks/*", and ".env" does not
# cover nested ".env" files; both need explicit entries.
IGNORE_PATTERNS = [
    # The GitHub project README must never reach the Space repo: the Space's
    # README.md is the frontmatter card (README_SPACE.md, uploaded first) and
    # the project readme has no frontmatter → instant CONFIG_ERROR if it wins.
    "README.md",
    ".git/*",
    ".git*",
    ".venv/*",
    ".claude/*",
    ".codex/*",
    "**/__pycache__/*",
    "**/*.pyc",
    ".pytest_cache/*",
    ".ruff_cache/*",
    ".DS_Store",
    "**/.DS_Store",
    # secrets — root AND nested (e.g. embedding_visualization/.env.local)
    ".env",
    ".env.*",
    "**/.env",
    "**/.env.*",
    # not needed to build the image
    "docs/*",
    "documentation/*",
    "gallery/*",
    "benchmarks/*",
    "references/*",
    "neuronpedia/*",
    "node_modules/*",
    "Papers/*",
    # experiments + local data (includes copyrighted corpora, e.g. Lacan TSVs
    # under interpretability_experiments/ — must never reach the public repo)
    "interpretability_backend/interpretability_experiments/*",
    "interpretability_backend/test/*",
    "interpretability_backend/benchmarks/*",
    # frontend build artifacts / deps (rebuilt in the image)
    "embedding_visualization/node_modules/*",
    "embedding_visualization/.next/*",
    "embedding_visualization/out/*",
    "embedding_visualization/coverage/*",
    "embedding_visualization/Users/*",
    "**/tsconfig.tsbuildinfo",
    "**/target/*",
    # backend live stores + local-only data (the demo seed is downloaded from
    # its locked private Dataset revision during the Docker build)
    "interpretability_backend/resources/main.duckdb",
    "interpretability_backend/resources/main.duckdb.*",
    "interpretability_backend/resources/vector_db/*",
    "interpretability_backend/resources/seed/*",
    "interpretability_backend/resources/seed_demo/*",
    "interpretability_backend/resources/uploads/*",
    "interpretability_backend/resources/job_state.json",
    "interpretability_backend/resources/sae_labels/*",
    "interpretability_backend/resources/sae_vectors/*",
    "interpretability_backend/resources/refusal_direction/*",
    "interpretability_backend/resources/experiments/*",
    "interpretability_backend/resources/extracted_activations/*",
    "interpretability_backend/resources/probing_results/*",
    "interpretability_backend/resources/psycolinguistics/*",
    "interpretability_backend/resources/acl_anthology/*",
    "interpretability_backend/resources/datasets/*",
]


def space_direct_url(repo_id: str) -> str:
    """The *.hf.space host — HF's stable embedding surface for the Space."""
    subdomain = re.sub(r"[^a-z0-9-]", "-", repo_id.lower())
    return f"https://{subdomain}.hf.space"


def social_preview_url(repo_id: str) -> str:
    """Hub-served URL of the social-preview image inside the Space repo."""
    return f"https://huggingface.co/spaces/{repo_id}/resolve/main/{SOCIAL_PREVIEW_PATH}"


def render_space_readme(repo_id: str) -> bytes:
    """README_SPACE.md with its URL placeholders resolved for this Space.

    The repo id lives only in CI variables (HF_SPACE_REPO_ID), so the README
    keeps {{SPACE_URL}} / {{SPACE_DIRECT_URL}} / {{SOCIAL_PREVIEW_URL}}
    placeholders and the deploy resolves them — that is what makes the "What
    to try" preset links and the card thumbnail work.
    """
    text = (DEPLOY_DIR / "README_SPACE.md").read_text(encoding="utf-8")
    text = text.replace("{{SPACE_URL}}", f"https://huggingface.co/spaces/{repo_id}")
    text = text.replace("{{SPACE_DIRECT_URL}}", space_direct_url(repo_id))
    text = text.replace("{{SOCIAL_PREVIEW_URL}}", social_preview_url(repo_id))
    validate_space_readme(text)
    return text.encode("utf-8")


def validate_space_readme(text: str) -> None:
    """Fail fast on the frontmatter constraints the Hub enforces server-side.

    The Hub validates README.md YAML on the commit that touches it; failing
    there used to strand a half-deployed Space in CONFIG_ERROR (observed:
    a 66-char short_description). Catch what we can locally, before any
    upload happens.
    """
    if not text.startswith("---\n"):
        sys.exit("ERROR: README_SPACE.md must start with a '---' frontmatter block.")
    match = re.search(r"^short_description:\s*(.+?)\s*$", text, re.MULTILINE)
    if match and len(match.group(1)) > 60:
        sys.exit(
            f"ERROR: short_description is {len(match.group(1))} chars; "
            "the Hub rejects anything over 60."
        )
    match = re.search(r"^thumbnail:\s*(.+?)\s*$", text, re.MULTILINE)
    if match and not match.group(1).startswith("https://"):
        sys.exit(
            f"ERROR: thumbnail must be an absolute https URL, got {match.group(1)!r} "
            "(social crawlers do not resolve relative paths or placeholders)."
        )


def ensure_site_url_variable(api: HfApi, repo_id: str) -> None:
    """Store the Space's public origin as the Space Variable NEXT_PUBLIC_SITE_URL.

    The frontend needs an absolute origin at BUILD time to emit crawler-
    fetchable og:image URLs (Next's metadataBase; without it production builds
    resolve social images to http://localhost:3000). HF's built-in SPACE_HOST
    is runtime-only, but user Variables are passed to the Docker build as
    build-args — so the deploy pins the origin itself. Runs before the tree
    upload so the rebuild those commits trigger already sees the value.

    Best-effort: a token without settings access must not block the deploy,
    so failures are reported as warnings (the app still works, only the
    direct-host link preview lacks its image).
    """
    wanted = space_direct_url(repo_id)
    try:
        current = api.get_space_variables(repo_id=repo_id).get(SITE_URL_VARIABLE)
        if current is not None and current.value == wanted:
            print(f"[deploy] Space variable {SITE_URL_VARIABLE} already set to {wanted}")
            return
        api.add_space_variable(
            repo_id=repo_id,
            key=SITE_URL_VARIABLE,
            value=wanted,
            description="Public origin baked into the frontend's social-preview metadata (set by deploy.py)",
        )
        print(f"[deploy] Space variable {SITE_URL_VARIABLE} = {wanted}")
    except HfHubHTTPError as exc:
        print(
            f"WARNING: could not set Space variable {SITE_URL_VARIABLE} ({exc}); "
            "set it manually under Settings → Variables and secrets, then rebuild.",
            file=sys.stderr,
        )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--repo-id", required=True, help="Space repo, e.g. <user>/orrery-demo")
    parser.add_argument("--create", action="store_true", help="create the Space if it is missing")
    parser.add_argument("--private", action="store_true", help="create the Space as private")
    args = parser.parse_args()

    lock_path = (
        REPO_ROOT / "interpretability_backend" / "config" / "seed_snapshots" / "demo.lock.json"
    )
    if not lock_path.exists():
        print(
            f"ERROR: immutable demo seed lock not found at {lock_path}.\n"
            "Build and publish demo.json first — see documentation/HF_SPACE_DEMO.md.",
            file=sys.stderr,
        )
        return 1

    api = HfApi()

    if args.create:
        api.create_repo(
            repo_id=args.repo_id,
            repo_type="space",
            space_sdk="docker",
            private=args.private,
            exist_ok=True,
        )
        print(f"[deploy] space ensured: {args.repo_id}")

    # Settings before commits: the Variable must exist when the rebuild that
    # the commits below trigger passes build-args to the Dockerfile.
    ensure_site_url_variable(api, args.repo_id)

    # README goes FIRST: the Hub validates its frontmatter on commit, so a
    # rejected card must fail the deploy before the tree is touched (the tree
    # upload excludes the project README.md, so this file is never clobbered).
    print("[deploy] uploading Space README (frontmatter card)…")
    api.upload_file(
        path_or_fileobj=render_space_readme(args.repo_id),
        path_in_repo="README.md",
        repo_id=args.repo_id,
        repo_type="space",
        commit_message="Space README",
    )

    print(f"[deploy] uploading filtered tree from {REPO_ROOT} (large files go via LFS)…")
    api.upload_folder(
        folder_path=str(REPO_ROOT),
        repo_id=args.repo_id,
        repo_type="space",
        ignore_patterns=IGNORE_PATTERNS,
        delete_patterns=["interpretability_backend/resources/seed_demo/**"],
        commit_message="Deploy Orrery demo",
    )

    print("[deploy] uploading .dockerignore…")
    api.upload_file(
        path_or_fileobj=str(REPO_ROOT / ".dockerignore"),
        path_in_repo=".dockerignore",
        repo_id=args.repo_id,
        repo_type="space",
        commit_message="Space .dockerignore",
    )

    space_url = f"https://huggingface.co/spaces/{args.repo_id}"
    print(
        f"\nDeployed. Watch the build at {space_url}\n"
        "Reminder: set the Space secret GEMINI_API_KEY to enable semantic "
        "search on the EMNLP + xkcd collections."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
